### PR TITLE
Add Authorizer section to API Gateway Request

### PR DESCRIPTION
**Pull request by audente**
Add Authorizer section to API Gateway Request

### Motivation:

As discussed in [issue #147](https://github.com/swift-server/swift-aws-lambda-runtime/issues/147), API Gateway is not decoding the Autorizer section.

That section is required when, for example, inside a Lambda function you need details about a user who is calling the function through a secured API Gateway.

### Modifications:

Added an 'authorizer' key to APIGateway.Request. This key is an optional dictionary of string to string.

### Result:

- After the change, the authorizer key is decoded into API Gateway Request.
- In my tests on AWS, this key contains all the Cognito information sent by API Gateway to my Lambda function.
- Since this is an optional key, it does not affect existing code that does not receive the authorizer data.

### CODE REVIEW

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
thanks @audente could you add or update the relevant unit test to test this

**Review by tomerd — CHANGES_REQUESTED** [review]
looks good, just needs a small unit test

**Comment by fabianfett** [comment]
@audente 👋 Ping: Are you still interested in getting this merged? I would love to see this land...

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by fabianfett** [comment]
Hi @audente, since the events have moved to a separate repository: Would you mind reopening your pr there? https://github.com/swift-server/swift-aws-lambda-events

**Pull request closed without merging**
