### PR TITLE
Adopt concurrency adoption guidelines

### PR DESCRIPTION
**Pull request by stevapple**
Adopt Swift Concurrency adoption guidelines for Swift Server Libraries (swift-server/guides#70).

### Motivation:

Adopt Swift Concurrency adoption guidelines (for the correct way to import `_Concurrency`).

### Modifications:

- Use `#if compiler(>=5.5) && canImport(_Concurrency)` to judge if Concurrency is available;
- Some cleaning.

### CODE REVIEW

**Comment by stevapple** [comment]
cc @tomerd @fabianfett

**Review by fabianfett — APPROVED** [review]
LGTM. Thanks @stevapple

**Comment by fabianfett** [comment]
@swift-server-bot test this please

**Comment by fabianfett** [comment]
@stevapple Let's do the sendable checks in another pr please! We don't mind them for merging right now.

**Comment by fabianfett** [comment]
@swift-server-bot test this please (@tomerd @yim-lee could I get bot rights for this repo and lambda-events as well please?)

**Comment by yim-lee** [comment]
> could I get bot rights for this repo and lambda-events as well please?

@ fabianfett I believe you have them already. Are you experiencing issues?

**Comment by fabianfett** [comment]
Nightly failed because of Sendable checking.

**Pull request merged**
