### PR TITLE
Local lambda invocation endpoint env var

### PR DESCRIPTION
**Pull request by jsonfry**
Allow the changing of the local lambda server's invocation endpoint

### Motivation:

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

As described in https://github.com/swift-server/swift-aws-lambda-runtime/issues/320 I want to be able to use other tooling that expects the local invocation endpoint to have a specific path, not just `/invoke`.

### Modifications:

I have added an envionrment variable option that lets you override the invocation endpoint url.

### Result:

If you set LOCAL_LAMBDA_SERVER_ENABLED to run locally, you can now also set LOCAL_LAMBDA_SERVER_INVOCATION_ENDPOINT to any value to change the path, e.g. to `/2015-03-31/functions/function/invocations` to match how the "[runtime interface emulator](https://docs.aws.amazon.com/lambda/latest/dg/images-test.html)" works.

### CODE REVIEW

**Comment by jsonfry** [comment]
fixes #320

**Comment by tomerd** [comment]
seems reasonable to me. @sebsto ?

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by jsonfry** [comment]
> What happens when LOCAL_LAMBDA_SERVER_INVOCATION_ENDPOINT is not defined ?

`Lambda.env("LOCAL_LAMBDA_SERVER_INVOCATION_ENDPOINT")` returns `nil`, so eventually this line of code is reached: [`self.invocationEndpoint = invocationEndpoint ?? "/invoke"`](https://github.com/swift-server/swift-aws-lambda-runtime/blob/e6a59c2cf0f35740d4ea72a702f69e45c20a974d/Sources/AWSLambdaRuntimeCore/Lambda%2BLocalServer.swift#L65) and it's set to `/invoke`, as before.

Or in short, it behaves as it did before.

**Comment by sebsto** [comment]
Oh, I missed [that line of code](https://github.com/swift-server/swift-aws-lambda-runtime/blob/e6a59c2cf0f35740d4ea72a702f69e45c20a974d/Sources/AWSLambdaRuntimeCore/Lambda%2BLocalServer.swift#L65). Good for me then.

**Comment by sebsto** [comment]
@tomerd feel free to approve when you have time - thanks

**Review by tomerd — APPROVED** [review]

**Comment by sebsto** [comment]
@swift-server-bot test this please

**Comment by sebsto** [comment]
@tomerd can you trigger a set of test. Apparently, I don't have permissions to do so. Thanks

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Pull request merged**
