### PR TITLE
fixed typo in readme

### PR DESCRIPTION
**Pull request by MarwaneKoutar**
changed 2 typos in readme.md (typo).

### Motivation:

There is two small typo's in readme.md.

### Modifications:

"contains" to "contain" and "upload" to "uploaded".

### Result:

No typo in that section.

### CODE REVIEW

**Review by etcwilde — APPROVED** [review]

**Comment by yim-lee** [comment]
@swift-server-bot add to allowlist

**Comment by yim-lee** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
nightly build error unrelated.

**Comment by yim-lee** [comment]
Thanks @MarwaneKoutar

**Pull request merged**
