### PR TITLE
add new abstraction for simple Lambda that does not need explicit initialization

### PR DESCRIPTION
**Pull request by tomerd**
motivation: make simple things simple

changes:
* add new abstraction names SimpleLambdaHandler that has a default initializer
* add test

### CODE REVIEW

**Comment by tomerd** [comment]
we could / should consider doing this on `LambdaHander` instead of the new abstraction, also not in love with the "Simple" prefix.

**Comment by stevapple** [comment]
We can drop `context:` from `LambdaHandler`’s initializer, then the `SimpleLambdaHandler` model will just fit (we can keep `async` and `throws` so users can still initialize some resources if they want).

**Comment by tomerd** [comment]
@stevapple `context` is needed when users need to initialize resources, it provides thinks like the NIO EventLoop and Terminator, so we cannot drop it.

**Comment by stevapple** [comment]
Is there any reason they cannot use async/await for asynchronous startup, and use throw in place of manual termination? I think that's the "simple" way and should work for most people.

**Comment by tomerd** [comment]
termination is for resource cleanup when shutting down, there needs to be an entry point to that. also all NIO based clients (eg db client based on NIO) need access the the `EventLoop` for initialization to avoid thread hops

**Review by fabianfett — COMMENTED** [review]
While I like the idea of making Lambda easier to use, I wonder if we actually achieve this goal through this change. Until now, IMO, it was clear which Handler protocol we recommend: LambdaHandler. Now the story is becoming harder.

Let's look at the pros and cons of this change:

Pro:

- We can remove 1-3 lines for very simple LambdaHandlers.
- Users don't need to specify an explicit init

Con:

- We need to explain to users the difference between `SimpleLambdaHandler` and `LambdaHandler` even in the Simple case. We need explain to users, that they shall use `SimpleLambdaHandler` if they don't have any resources that they want to share between invocations.
- The way from a very simple lambda to an actual lambda (I think every real lambda, will use some shared network resources) is becoming harder. We need to remind developers, that they need to change the `Handler` protocol and now need to implement a new init method. There is no compiler warning to point them into the right direction.

In my opinion the cons outweigh the pros. Is there something that I have overseen?

**Comment by tomerd** [comment]
superseded by #273

**Pull request closed without merging**
