### PR TITLE
Fixes AWS Event namespace problems

### LINKED ISSUE #119: Name clash with AWSSDKSwift v4.x
The AWSLambdaEvents define enum namespaces for the Events (`S3`, `SNS`, `SES`, `SQS`...). These mean you cannot use v4.x of AWSSDKSwift with swift-aws-lambda-runtime. This is partly the fault of AWSSDKSwift as in v4.x the framework name is the same as the main struct name, so you cannot differentiate between `S3` in AWSSKDSwift and `S3` in AWSLambdaEvents.

This is resolved with the AWSSDKSwift v5.0 alpha as the framework names have been prepended with `AWS`. Thus won't be an issue in the future.

I'm not sure if anything will be done about this now, given the issue will disappear in the future, but I must say using such general terms for a very specific part of a service wasn't necessarily the best idea.

### PR DESCRIPTION
**Pull request by fabianfett**
Fixes #119.

### CODE REVIEW

**Review by tomerd — COMMENTED** [review]
this seems fine, but maybe still conflicting without some sort of "Lambda" prefix or namespace?

**Comment by fabianfett** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@fabianfett is this read to merge?

**Comment by fabianfett** [comment]
@tomerd Yes!

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
lets port this over to https://github.com/swift-server/swift-aws-lambda-events once after #216 is merged

**Comment by fabianfett** [comment]
Will be fixed in the new events repo: https://github.com/swift-server/swift-aws-lambda-events/pull/2

**Pull request closed without merging**
