### PR TITLE
Dynamodb put backend example

### PR DESCRIPTION
**Pull request by tachyonics**
## Description

Moving over PR from samples repository.

## Testing

Deployed lambda to AWS account
Verified lambda succeeded and expected logs were produced.

### CODE REVIEW

**Comment by tomerd** [comment]
thank you @tachyonics, needs a rebase (sorry)

also the sanity script is failing on some formatting issues, you should be able to run it locally or in docker

**Comment by weissi** [comment]
CC @orac

**Comment by eneko** [comment]
This is pretty cool, @tachyonics, I'm quite excited about this. I'm not a contributor to this library, but wanted to give this a try and provide some feedback.

I pulled this PR and have been running some tests, trying to learn how this works. I managed to get everything working with `sam-deploy.sh`, I can run the lambda and see data populated on DynamoDB. Pretty straight-forward.

However, I haven't been able to get it to work with `deploy.sh`. I manually configured AIM roles and permissions, but seems like I'm missing something. It woukld be great if README was updated with set up instructions.

Thank you!

**Comment by eneko** [comment]
[Just got it working](https://forums.swift.org/t/trying-to-connect-to-dynamodb/37264/5?u=eneko) with `deploy.sh`, all I needed was to properly configure environment variables for the DynamoDB table I had granted permissions. Hoping this gets accepted (though more documentation would be great)

**Comment by tomerd** [comment]
hi @tachyonics how do you want to proceed with this PR? note some thoughts about such additional examples in https://forums.swift.org/t/examples-and-getting-started-guides/

**Comment by tomerd** [comment]
@tachyonics if you want to keep this around, could you please update this PR to be against the `main` branch so we can delete the old `master` branch

**Pull request closed without merging**
