### PR TITLE
Require Swift 6

### PR DESCRIPTION
**Pull request by aryan-25**
### Motivation:

- This PR paves the way to land the new API discussed in #339.
- AWS Lambda Runtime v2 will require Swift 6 as it will enforce full Sendability checking.
- For us to land the PRs that work towards our new API, we need to require Swift 6.

### Modifications:

- Change `swift-tools-version` from `5.9` to `6.0` in `Package.swift`.
- Use Swift 5 Language Mode for all targets.
- Modify `Plugin.swift` to compile error-free with Swift 6.

### Result:

First step towards adopting Swift 6.

### CODE REVIEW

**Comment by fabianfett** [comment]
@swift-server-bot add to whitelist

**Review by sebsto — APPROVED** [review]
LGTM

**Comment by fabianfett** [comment]
Let's land #340 and then rebase on top of it.

**Review by fabianfett — APPROVED** [review]
LGTM, Let's get CI in order

**Review by fabianfett — APPROVED** [review]

**Comment by fabianfett** [comment]
API breakage and doc check fail because of 5.10 requirement. Merging to unblock further work for now. Will enforce at a later point in time again.

**Pull request merged**
