### PR TITLE
Add script to check for API breaks

### PR DESCRIPTION
**Pull request by fabianfett**
We should check for API breaking changes in CI, to ensure we don't accidentally break API going forwards.

### Motivation:

- We should check for API breaking changes in CI, to ensure we don't accidentally break API going forwards.

### Modifications:

- Add a script that checks for breaking changes (copy and pasted from NIO).

### Result:

- We ensure we don't accidentally break API after 1.0

### Open tasks:

@tomerd we need to add another CI that runs the API checking script.

### CODE REVIEW

**Comment by tomerd** [comment]
thanks @fabianfett, should we add a docker compose task that runs this, or do we need to do that at the CI server level?

**Comment by fabianfett** [comment]
@tomerd I tried to see what we do in AHC. However I did not find a special docker-compose task for it. So I assume it is activated in the CI server.

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Comment by tomerd** [comment]
@swift-server-bot test this please

**Review by tomerd — APPROVED** [review]

**Pull request merged**
